default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: <%= ENV['DB_HOST'] %>
  # database: db
  # username: <%= ENV['DB_USR'] %>
  # password: <%= ENV['DB_PWD'] %>
  # port: <%= ENV['DB_PORT'] %>
  url: <%= ENV['DB_URL'] %>


development:
  <<: *default

test:
  <<: *default


production:
  <<: *default
